name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
#  schedule:
#    - cron: '0 * * * *'

jobs:
  build:
    name: Build GitHub Agents
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - if: github.ref == 'refs/heads/master'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK 5.0.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Run Cake script
        run: |
          echo ::group::".NET Tool Restore"
          dotnet tool restore
          echo ::endgroup::
          dotnet cake --remove-base-image=true

  build-self-hosted:
    name: Build Self Hosted Agent
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted]
    steps:
      - if: github.ref == 'refs/heads/master'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Run Cake script
        run: |
          echo ::group::".NET Tool Restore"
          dotnet tool restore
          echo ::endgroup::
          dotnet cake