name: Build on GitHub Windows 2019 Agent
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
  schedule:
    - cron:  '0 7 * * WED'

jobs:
  build:
    name: Build Images
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        sdk: ['6.0', '7.0']
    steps:
      - if: github.ref == 'refs/heads/main'
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v3

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          cake-version: tool-manifest
          arguments: |
            remove-base-image: true
            base-image-include-filter: ${{ matrix.sdk }}-windowsservercore-ltsc2019