name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
#  schedule:
#    - cron: '0 * * * *'

jobs:
  build:
    name: Build GitHub Agents
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]
        sdk: ['3.1', '5.0', '6.0']
    steps:
      - if: github.ref == 'refs/heads/master'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          cake-version: tool-manifest
          arguments: |
            remove-base-image: true
            base-image-include-filter: ${{ matrix.sdk }}
            base-image-exclude-filter: ${{ matrix.sdk }}-nanoserver-1
            base-image-exclude-filter: ${{ matrix.sdk }}-nanoserver-2
            base-image-exclude-filter: ${{ matrix.sdk }}-windowsservercore-ltsc2019

  build-windows-2019:
    name: "Build GitHub Agents"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        sdk: ['3.1', '5.0', '6.0']
    steps:
      - if: github.ref == 'refs/heads/master'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          cake-version: tool-manifest
          arguments: |
            remove-base-image: true
            base-image-include-filter: ${{ matrix.sdk }}-windowsservercore-ltsc2019

  build-self-hosted:
    name: Build Self Hosted Agent
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [self-hosted]
        sdk: ['3.1', '5.0', '6.0']
    steps:
      - if: github.ref == 'refs/heads/master'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          cake-version: tool-manifest
          arguments: |
            base-image-include-filter: ${{ matrix.sdk }}-nanoserver-1
            base-image-include-filter: ${{ matrix.sdk }}-nanoserver-2
